// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef DRIVECOMMAND_H
#define DRIVECOMMAND_H


#include "Commands/Subsystem.h"
#include "../Robot.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class DriveCommand: public Command {
public:
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	DriveCommand();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();

private:
	float XAxis; //joystick value
	float YAxis; //joystick value
	float RotAxis; //joystick value
	float SetAngle; //angle passed into rotation
	float SetSpeed; //speed passed into rotation
	float FinalAutoRot; //number passed into mec drive cartesian
	float AdjustedYaw; //number passed into yaw param of mec drive cartesian (fixes auto modes)
	bool ButtonYPressed; //buttons for rotating
	bool ButtonXPressed;
	bool ButtonAPressed;
	bool ButtonBPressed;
	bool isRotDone;
};

#endif
